# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'CollectionViewInfiniteScrolling' do

pod 'SVPullToRefresh', :git => 'https://github.com/jfl913/SVPullToRefresh'

end

target 'CollectionViewInfiniteScrollingTests' do

end

