# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'NSProgressDemo' do

pod "AFNetworking", "~> 2.0"
pod 'SVProgressHUD'

end

target 'NSProgressDemoTests' do

end

